### PR TITLE
Use OsString instead of String so that paths are actually represented correctly

### LINKED ISSUE #42: Support non-utf8 file names
If given a non-utf8 filename, such as

```
$ touch `echo -e "notutf8\xbf.dat"`
```

`SftpSession::read_dir(path_to_directory)` will fail to list the directory, as `filename` in `DirEntry` is of type string and `try_get_string` throws an error when encountering a non-utf8 string.

```
    fn try_get_string(&mut self) -> Result<String, Error> {
        let bytes = self.try_get_bytes()?;
        String::from_utf8(bytes).map_err(|_| Error::BadMessage("unable to parse str".to_owned()))
    }
```

A solution could be to use OsString or PathBuf, I'll try to write a PR, but I've barely started climbing the Rust learning curve :)

### PR DESCRIPTION
**Pull request by kanpov**
Fixes #42

### CODE REVIEW

**Comment by kanpov** [comment]
IMO OsString is the objectively correct type to use:

1. OS-independent, unlike PathBuf
2. Supports non-UTF-8 characters properly

**Comment by kanpov** [comment]
The bad news is even though this is an absolutely mandatory change to do (since keeping string paths is strictly not an option), it's undoubtedly a breaking change, so if the project's maintainers want to follow semver, a `3.0.0` version bump will be needed

**Comment by kanpov** [comment]
I can testify to this functioning correctly at least on SFTP client because the suite of 24 tests that cover the vast majority of the russh-sftp API pass:

https://github.com/kanpov/remoteify/blob/master/tests/filesystem_russh.rs

**Comment by AspectUnk** [comment]
There are issues with this solution, I described them better [here](https://github.com/AspectUnk/russh-sftp/issues/42#issuecomment-2227050528).

**Pull request closed without merging**
